#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$(pwd)/kernel_platform}"
KERNEL="$ROOT/msm-kernel"
VENDOR_DTS="$KERNEL/arch/arm64/boot/dts/vendor"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WLAN="$ROOT/vendor/qcom/opensource/wlan"
QCACLD="$WLAN/qcacld-3.0"
QCACLD_PROFILE_DEFCONFIG="$QCACLD/configs/blair_gki_wlan_defconfig"
QCACLD_AUTOCONF="$QCACLD/configs/creek_blair_gki_autoconf.h"
# Manual Kbuild does not get Kleaf/DDK's module defconfig -> C macro bridge.
# Generate a small autoconf-style header from Creek's qcacld profile so
# configs/config_to_feature.h sees the same CONFIG_* values as Bazel/DDK.
test -f "$QCACLD_PROFILE_DEFCONFIG"
python3 - "$QCACLD_PROFILE_DEFCONFIG" "$QCACLD_AUTOCONF" <<'PY_AUTOCONF'
import re
import sys
from pathlib import Path

src = Path(sys.argv[1])
out = Path(sys.argv[2])
lines = [
    "/* Auto-generated by prepare-creek-stock.sh from configs/blair_gki_wlan_defconfig. */\n",
    "#ifndef CREEK_BLAIR_GKI_AUTOCONF_H\n",
    "#define CREEK_BLAIR_GKI_AUTOCONF_H\n",
]
seen = set()
for raw in src.read_text().splitlines():
    raw = raw.strip()
    if not raw or raw.startswith("#") or not raw.startswith("CONFIG_"):
        continue
    if ":=" in raw:
        key, val = raw.split(":=", 1)
    elif "=" in raw:
        key, val = raw.split("=", 1)
    else:
        continue
    key = key.strip()
    val = val.strip()
    if not re.fullmatch(r"CONFIG_[A-Za-z0-9_]+", key):
        continue
    if key in seen:
        continue
    seen.add(key)
    if val == "y":
        lines.append(f"#ifndef {key}\n#define {key} 1\n#endif\n")
    elif val == "m":
        lines.append(f"#ifndef {key}_MODULE\n#define {key}_MODULE 1\n#endif\n")
    elif re.fullmatch(r"0[xX][0-9A-Fa-f]+|[0-9]+", val):
        lines.append(f"#ifndef {key}\n#define {key} {val}\n#endif\n")
    elif len(val) >= 2 and val[0] == val[-1] == '"':
        lines.append(f"#ifndef {key}\n#define {key} {val}\n#endif\n")
lines.append("#endif /* CREEK_BLAIR_GKI_AUTOCONF_H */\n")
out.write_text("".join(lines))
PY_AUTOCONF

grep -q '^#define CONFIG_LITTLE_ENDIAN 1$' "$QCACLD_AUTOCONF"
grep -q '^#define CONFIG_WLAN_TRACE_HIDE_MAC_ADDRESS_DISABLE 1$' "$QCACLD_AUTOCONF"
grep -q '^#define CONFIG_WLAN_DEBUGFS 1$' "$QCACLD_AUTOCONF"

mkdir -p "$VENDOR_DTS"

# Keep Creek's original wireless split configuration intact. cfg80211 and
# mac80211 are built as MSM/vendor modules, and dependent WLAN modules must
# use the same MSM Module.symvers. Do not convert cfg80211 to built-in in the
# vendor fragment; that duplicates wireless exports during modpost.

# build.sh recursively invokes the GKI build. Do not let the outer external
# module makefile run during that recursive common-kernel build: vendor modules
# must be built only after GKI artifacts exist, against msm-kernel with
# KBUILD_MIXED_TREE set. The upstream script clears EXT_MODULES but older
# branches do not clear EXT_MODULES_MAKEFILE.
BUILD_SH="$ROOT/build/build.sh"
REAL_BUILD_SH="$(readlink -f "$BUILD_SH")"
if [ ! -f "$REAL_BUILD_SH" ]; then
  echo "ERROR: resolved build.sh target not found: $REAL_BUILD_SH" >&2
  exit 1
fi

# Creek's custom GKI adds symbols from NetHunter subsystems (TCP congestion
# control and other common-kernel features). Wireless cores and MT76 stay in
# the MSM module build. Use nullptr-t-oss' ABI bypass v2 so the
# stock symbol-list gate reports differences but does not abort this custom
# kernel build.
ABI_BYPASS_PATCH="$REPO_ROOT/patches/common/abi-bypass-v2.patch"
ABI_CHECKER="$ROOT/build/abi/compare_to_symbol_list"
if [ ! -f "$ABI_CHECKER" ]; then
  ABI_CHECKER="$ROOT/build/kernel/abi/compare_to_symbol_list"
fi
if [ ! -f "$ABI_CHECKER" ]; then
  echo "ERROR: ABI checker not found under kernel_platform" >&2
  exit 1
fi
ABI_CHECKER_REAL="$(readlink -f "$ABI_CHECKER")"
echo "[nethunter] ABI checker: $ABI_CHECKER -> $ABI_CHECKER_REAL"
if grep -q 'BUT WHO CARES?' "$ABI_CHECKER_REAL"; then
  echo "[nethunter] ABI bypass already applied"
elif grep -qE '^\s*exit 1$' "$ABI_CHECKER_REAL"; then
  # The repo manifest exposes this project through symlinks, so git -C on the
  # kernel_platform superdirectory is unreliable. Apply the same nullptr v2
  # change to the exact resolved checker used by build.sh, then verify it.
  ABI_CHECKER_TMP="${ABI_CHECKER_REAL}.tmp"
  awk '{ if ($0 ~ /^[[:space:]]*exit 1$/) { print "\techo \"BUT WHO CARES?\" >&2"; print "\texit 0" } else print }' \
    "$ABI_CHECKER_REAL" > "$ABI_CHECKER_TMP"
  mv "$ABI_CHECKER_TMP" "$ABI_CHECKER_REAL"
  chmod +x "$ABI_CHECKER_REAL"
  echo "[nethunter] ABI bypass applied: $ABI_CHECKER_REAL"
else
  echo "ERROR: ABI checker has unexpected contents: $ABI_CHECKER_REAL" >&2
  tail -20 "$ABI_CHECKER_REAL" >&2
  exit 1
fi
if ! grep -q 'BUT WHO CARES?' "$ABI_CHECKER_REAL"; then
  echo "ERROR: ABI bypass verification failed" >&2
  exit 1
fi
# build.sh overwrites MAKEFLAGS with nproc, which can terminate the runner
# during the GKI LTO link. Respect the workflow's explicit jobs input for both
# the outer vendor build and the recursive inner GKI build.
if ! grep -q 'creek_nethunter_jobs_fix' "$REAL_BUILD_SH"; then
  sed -i 's/export MAKEFLAGS="-j$(nproc) ${MAKEFLAGS}"/#[ creek_nethunter_jobs_fix ]\nexport MAKEFLAGS="-j${KERNEL_BUILD_JOBS:-$(nproc)} ${MAKEFLAGS}"/' "$REAL_BUILD_SH"
  sed -i '/GKI_ENVIRON+=("EXT_MODULES=")/a\  GKI_ENVIRON+=("KERNEL_BUILD_JOBS=${KERNEL_BUILD_JOBS}")' "$REAL_BUILD_SH"
fi

if grep -q 'GKI_ENVIRON+=("EXT_MODULES=")' "$REAL_BUILD_SH" \
   && ! grep -q 'GKI_ENVIRON+=("EXT_MODULES_MAKEFILE=")' "$REAL_BUILD_SH"; then
  sed -i '/GKI_ENVIRON+=("EXT_MODULES=")/a\  GKI_ENVIRON+=("EXT_MODULES_MAKEFILE=")' "$REAL_BUILD_SH"
  sed -i '/GKI_ENVIRON+=("EXT_MODULES_MAKEFILE=")/a\  GKI_ENVIRON+=("BUILD_BOOT_IMG=" "BUILD_VENDOR_BOOT_IMG=" "BUILD_INIT_BOOT_IMG=" "BUILD_VENDOR_KERNEL_BOOT=" "BUILD_DTBO_IMG=" "SKIP_VENDOR_BOOT=1")' "$REAL_BUILD_SH"
fi

# Xiaomi's Creek build enables MODULES_LIST_ORDER=1 and stock module lists
# are basename-only (the same format shipped in stock vendor_boot). Kbuild
# modules.order is path-qualified, and depmod requires those paths when modules
# are staged below lib/modules/${version}/kernel or extra. Patch build_utils.sh
# so it keeps a path-qualified modules.order internally for depmod/trimming, but
# emits basename-only modules.load files for stock-compatible Android init. Also
# treat MODULES_RECOVERY_LIST as a full stock recovery list (not only additions)
# when list_order=1, because Creek stock modules.load.recovery is standalone.
#
# build.sh sources ${ROOT_DIR}/build/build_utils.sh. Some trees expose build.sh
# through symlinks, so patch both the sourced path and the resolved-neighbor path
# when present.
for BUILD_UTILS in \
  "$ROOT/build/build_utils.sh" \
  "$(dirname "$REAL_BUILD_SH")/build_utils.sh"; do
  [ -f "$BUILD_UTILS" ] || continue
  python3 - "$BUILD_UTILS" <<'PY_BUILD_UTILS'
import sys
from pathlib import Path

p = Path(sys.argv[1])
s = p.read_text()
if "creek_modules_list_order_path_fix_v2" in s:
    raise SystemExit(0)

block_start = s.index("    local modules_list_filter=$(mktemp)")
block_end = s.index("  if [ -n \"${modules_blocklist_file}\" ]", block_start)
new = """    local modules_list_filter=$(mktemp)
    local old_modules_list=$(mktemp)

    # Remove all lines starting with "#" (comments)
    # Exclamation point makes interpreter ignore the exit code under set -e
    ! grep -v "^\\#" ${modules_list_file} > ${modules_list_filter}

    # creek_modules_list_order_path_fix_v2: for MODULES_LIST_ORDER=1, stock
    # lists are basename-only, but depmod needs the real module path relative to
    # lib/modules/${version}. Resolve each basename back to the original
    # path-qualified modules.order while preserving stock list order.
    cp ${dest_dir}/modules.order ${old_modules_list}
    if [ "${list_order}" = "1" ]; then
      awk -F/ '
        NR == FNR { if (!($NF in path)) path[$NF] = $0; next }
        !seen[$0]++ && ($0 in path) { print path[$0] }
      ' ${old_modules_list} ${modules_list_filter} > ${dest_dir}/modules.order
    else
      ! grep -w -f ${modules_list_filter} ${old_modules_list} > ${dest_dir}/modules.order
    fi
    if [[ -n "${modules_recoverylist_file}" ]]; then
      if [ "${list_order}" = "1" ]; then
        if [[ -f "${ROOT_DIR}/${modules_recoverylist_file}" ]]; then
          modules_recoverylist_file="${ROOT_DIR}/${modules_recoverylist_file}"
        elif [[ "${modules_recoverylist_file}" != /* ]]; then
          echo "modules recovery list must be an absolute path or relative to ${ROOT_DIR}: ${modules_recoverylist_file}" >&2
          exit 1
        elif [[ ! -f "${modules_recoverylist_file}" ]]; then
          echo "Failed to find modules list: ${modules_recoverylist_file}" >&2
          exit 1
        fi
        local modules_recoverylist_filter=$(mktemp)
        ! grep -v "^\\#" ${modules_recoverylist_file} > ${modules_recoverylist_filter}
        awk -F/ '
          NR == FNR { if (!($NF in path)) path[$NF] = $0; next }
          !seen[$0]++ && ($0 in path) { print path[$0] }
        ' ${old_modules_list} ${modules_recoverylist_filter} > ${dest_dir}/modules.order.recovery
        rm -f ${modules_recoverylist_filter}
      else
        create_additional_modules_order "${modules_list_filter}" "${modules_recoverylist_file}" \
          "${old_modules_list}" "${dest_dir}/modules.order.recovery"
      fi
    fi
    if [[ -n "${modules_chargerlist_file}" ]]; then
      if [ "${list_order}" = "1" ]; then
        if [[ -f "${ROOT_DIR}/${modules_chargerlist_file}" ]]; then
          modules_chargerlist_file="${ROOT_DIR}/${modules_chargerlist_file}"
        elif [[ "${modules_chargerlist_file}" != /* ]]; then
          echo "modules charger list must be an absolute path or relative to ${ROOT_DIR}: ${modules_chargerlist_file}" >&2
          exit 1
        elif [[ ! -f "${modules_chargerlist_file}" ]]; then
          echo "Failed to find modules list: ${modules_chargerlist_file}" >&2
          exit 1
        fi
        local modules_chargerlist_filter=$(mktemp)
        ! grep -v "^\\#" ${modules_chargerlist_file} > ${modules_chargerlist_filter}
        awk -F/ '
          NR == FNR { if (!($NF in path)) path[$NF] = $0; next }
          !seen[$0]++ && ($0 in path) { print path[$0] }
        ' ${old_modules_list} ${modules_chargerlist_filter} > ${dest_dir}/modules.order.charger
        rm -f ${modules_chargerlist_filter}
      else
        create_additional_modules_order "${modules_list_filter}" "${modules_chargerlist_file}" \
          "${old_modules_list}" "${dest_dir}/modules.order.charger"
      fi
    fi
    rm -f ${modules_list_filter} ${old_modules_list}
  fi

"""
s = s[:block_start] + new + s[block_end:]

trim_start = s.index('        find . -type f -name \'*.ko\' -printf "%f\\n" > modules.name.full')
trim_end = s.index('        # This is done to insert escaped directory boundary', trim_start)
trim_new = """        find . -type f -name '*.ko' -printf \"%f\\n\" > modules.name.full
        {
          awk -F/ '{ print $NF }' modules.order
          [[ -f modules.order.recovery ]] && awk -F/ '{ print $NF }' modules.order.recovery
          [[ -f modules.order.charger ]] && awk -F/ '{ print $NF }' modules.order.charger
          cat $used_blocklist_modules
        } > modules.name.need
        grep -v -x -f modules.name.need modules.name.full > modules.name.remove
"""
s = s[:trim_start] + trim_new + s[trim_end:]

depmod_start = s.index('  # Run depmod to ensure that dependencies between all modules loaded during')
depmod_end = s.index('\n}\n\nfunction build_system_dlkm()', depmod_start)
depmod_new = """  # Run depmod to ensure that dependencies between all modules loaded during
  # first stage init when booting into any other mode besides normal boot can be
  # satisfied.
  if [[ -f ${dest_dir}/modules.order.recovery ]]; then
    run_depmod ${dest_stage} \"${depmod_flags}\" \"${version}\" \"${dest_dir}/modules.order.recovery\"
    if [ \"${list_order}\" = \"1\" ]; then
      awk -F/ '{ print $NF }' ${dest_dir}/modules.order.recovery > ${dest_dir}/modules.load.recovery
    else
      cp ${dest_dir}/modules.order.recovery ${dest_dir}/modules.load.recovery
    fi
  fi

  if [[ -f ${dest_dir}/modules.order.charger ]]; then
    run_depmod ${dest_stage} \"${depmod_flags}\" \"${version}\" \"${dest_dir}/modules.order.charger\"
    if [ \"${list_order}\" = \"1\" ]; then
      awk -F/ '{ print $NF }' ${dest_dir}/modules.order.charger > ${dest_dir}/modules.load.charger
    else
      cp ${dest_dir}/modules.order.charger ${dest_dir}/modules.load.charger
    fi
  fi

  # Re-run depmod to detect any dependencies between in-kernel and external
  # modules. Then, create modules.order based on all the modules compiled.
  run_depmod ${dest_stage} \"${depmod_flags}\" \"${version}\"
  if [ \"${list_order}\" = \"1\" ]; then
    awk -F/ '{ print $NF }' ${dest_dir}/modules.order > ${dest_dir}/modules.load
  else
    cp ${dest_dir}/modules.order ${dest_dir}/modules.load
  fi
"""
s = s[:depmod_start] + depmod_new + s[depmod_end:]

p.write_text(s)
PY_BUILD_UTILS
done

# QCOM DTs are out-of-tree in Xiaomi's kernel_devicetree repo.
# arch/arm64/boot/dts/Makefile only descends into vendor/ when vendor/Makefile exists.
# Without this, dtbs_install creates no dtb_staging directory and build.sh fails in install_dtbs.
if [ ! -e "$VENDOR_DTS/Makefile" ]; then
  ln -s "$ROOT/kernel-devicetree/Makefile" "$VENDOR_DTS/Makefile"
fi
if [ ! -e "$VENDOR_DTS/qcom" ]; then
  ln -s "$ROOT/kernel-devicetree/qcom" "$VENDOR_DTS/qcom"
fi
if [ ! -e "$VENDOR_DTS/bindings" ] && [ -e "$ROOT/kernel-devicetree/bindings" ]; then
  ln -s "$ROOT/kernel-devicetree/bindings" "$VENDOR_DTS/bindings"
fi

echo "Prepared Creek stock source layout"
echo "ROOT=$ROOT"
echo "KERNEL=$KERNEL"
echo "VENDOR_DTS=$VENDOR_DTS"
echo "BUILD_SH=$BUILD_SH -> $(readlink "$BUILD_SH" 2>/dev/null || true)"
echo "REAL_BUILD_SH=$REAL_BUILD_SH"
echo "REAL_GETTOP=$(dirname "$REAL_BUILD_SH")/gettop.sh"
test -f "$(dirname "$REAL_BUILD_SH")/gettop.sh"
ls -la "$VENDOR_DTS"
